# Why Do We Do Inference? Population vs. Sample

## Population

A population includes all individuals, objects, or observations that we want to draw conclusions about. In practice, we usually cannot access the entire population.

## Sample

A sample is a subset of the population that we have access to. We can compute statistics from the sample.

## Statistic

A statistic is a function of a random sample. We can calculate its exact value from the sample data. Examples: sample mean, sample median, sample variance, sample proportion.

## Parameter

A parameter is a numerical value that describes the entire population. The true value of a parameter is unknown to us. We use statistics to make inferences about parameters.

## Examples of Population and Sample

**Example 1: Patients with a specific disease**

Population: All patients with that disease worldwide (e.g., 5 million people)

Sample: 300 patients participating in a clinical trial

Why we cannot access the population: Not all patients are in one place, some are undiagnosed, and studying all of them is impossible.

**Example 2: Customers in an A/B test for an online store**

Population: All customers visiting the website during a specific time period (e.g., 200,000 people)

Sample: 5,000 customers randomly assigned to the test group

Goal: Generalize the test results to all customers.

**Example 3: Light bulbs produced in a factory**

Population: All 10,000 light bulbs produced in one month

Sample: 100 light bulbs selected for lifetime testing

Why we cannot access the population: Lifetime testing is destructive. If we test all bulbs, nothing remains to sell.

**Example 4: Height of women above 20 years old in Tehran**

Population: All women above 20 living in Tehran (e.g., 3 million people)

Sample: 100 randomly selected women

Why we cannot access the population: Measuring 3 million people takes too much time and money.

## The Main Question: When Should We Take a Difference Seriously?

Suppose someone claims that the mean height of all women above 20 in Tehran is exactly 160 cm. This claim is a population parameter.

You cannot measure all 3 million people. You take a sample of 100 women and calculate their mean height. This sample mean is a statistic.

Consider three scenarios:

1. The sample mean is 160.03. Do you reject the claim?

2. The sample mean is 215. Do you reject the claim?

3. The sample mean is 163. What do you decide?

Key point: If you take another sample of 100 women, its mean will probably be different. Because of random sampling, statistics vary from one sample to another.

The core question of inferential statistics is this: When is the difference between a statistic (e.g., 163) and a claimed parameter (e.g., 160) large enough to say the claim is false? And when should we attribute this difference to random sampling variation?

We need a threshold. If the difference exceeds that threshold, we reject the claim. If not, we say there is not enough evidence to reject the claim.

## Three Types of Inference

There are three main approaches to drawing conclusions about population parameters.

**1. Point Estimation**

We provide a single number as an estimate of the population parameter. This estimate is usually the statistic calculated from the sample. The weakness of this approach is that it gives no information about how close the estimate is to the true parameter value.

**2. Interval Estimation**

We provide an interval and state that the population parameter lies within that interval with a certain confidence level. The correct interpretation is: if we repeat the sampling process many times and calculate an interval each time, approximately (e.g., 95%) of those intervals will contain the true population parameter. This is not the same as saying the parameter has a certain probability of falling into a specific interval.

**3. Hypothesis Testing**

A battery factory claims that the mean lifetime of their batteries is 500 hours. You take a random sample and calculate the sample mean. Based on your sample, you want to decide whether the evidence is strong enough to reject the factory's claim or not. If the difference between your sample mean and 500 is larger than what can be explained by random sampling variation, you reject the claim. Otherwise, you say there is not enough evidence to reject it.

In this workshop, our main focus will be on the third type: hypothesis testing.

![alt text](Population_vs._Sample_01.png)

## One-Sample t-Test Manual Implementation

**Step 1: What is a Test Statistic**

A test statistic is a function of a random sample used to make a decision about a claim concerning the population. These functions have been introduced by statisticians for different situations, and their probability distributions are fully known. You are not expected to create such functions.

**Step 2: Notation**

Let:

- $X_1, X_2, ..., X_n$ be a random sample from a population with mean $\mu$ and variance $\sigma^2$
- $\bar{X}$ be the sample mean: $\bar{X} = \frac{1}{n}\sum_{i=1}^{n} X_i$
- $S$ be the sample standard deviation: $S = \sqrt{\frac{1}{n-1}\sum_{i=1}^{n} (X_i - \bar{X})^2}$
- $\mu_0$ be the claimed value of the population mean under the null hypothesis

**Step 3: The t-Test Statistic**

The test statistic for examining the claim $H_0: \mu = \mu_0$ against $H_1: \mu \neq \mu_0$ is defined as:

$$T = \frac{\bar{X} - \mu_0}{S / \sqrt{n}}$$

The denominator, $S / \sqrt{n}$, is called the standard error of the mean.

**Step 4: Sampling Distribution of the Test Statistic**

To understand the distribution of $T$, we first need to examine the behavior of $\bar{X}$.

If the population has mean $\mu$ and variance $\sigma^2$, then according to the Central Limit Theorem, the sampling distribution of the sample mean $\bar{X}$ is approximately normal for sufficiently large sample sizes, regardless of the population distribution:

$$\bar{X} \sim N(\mu, \frac{\sigma^2}{n})$$

More precisely:

$$E(\bar{X}) = \mu$$
$$Var(\bar{X}) = \frac{\sigma^2}{n}$$

The standard deviation of $\bar{X}$, which is $\sigma / \sqrt{n}$, is called the standard error of the mean. However, since $\sigma$ (the population standard deviation) is unknown, we estimate it using $S$ (the sample standard deviation). This is why we use the t-distribution instead of the normal distribution.

**Important Note on Normality Assumption**

The t-test relies on the assumption that the population from which the sample is drawn is approximately normal. This assumption is necessary for the t-statistic to exactly follow a t-distribution.

For large sample sizes (typically n ≥ 30), the Central Limit Theorem ensures that the sampling distribution of $\bar{X}$ is approximately normal, so the t-test remains valid even if the population is not normal. However, for small sample sizes, violations of the normality assumption can lead to unreliable results.

A safer approach when normality is violated, especially with small samples, is to use non-parametric alternatives. These tests do not assume a specific distribution for the population and are more robust. Non-parametric tests are recommended when you are unsure about the underlying distribution of your data.

As a general guideline: if you are unsure about normality and your sample size is small, it is safer to use non-parametric tests rather than relying on the Central Limit Theorem.

**Step 5: Decision Rule**

After computing the observed value $T_{\text{obs}}$ from the data, the p-value is calculated as:

$$p\text{-value} = 2 \times P(T_{(n-1)} \geq |T_{\text{obs}}|)$$

where $T_{(n-1)}$ is a random variable following a t-distribution with $n-1$ degrees of freedom.

If $p\text{-value} < \alpha$ (where $\alpha$ is the significance level, typically set to 0.05), then we reject $H_0$. Otherwise, we say there is not enough evidence to reject $H_0$.

**Step 6: Summary of Steps**

1. Check the normality assumption (for small samples)
2. Calculate $\bar{X}$ (sample mean)
3. Calculate $S$ (sample standard deviation)
4. Calculate $T = \frac{\bar{X} - \mu_0}{S / \sqrt{n}}$
5. Determine degrees of freedom $df = n - 1$
6. Calculate the p-value using the cumulative distribution function of the t-distribution
7. Compare the p-value with $\alpha$ and make the final decision

![alt text](images.png)

In [1]:
import pandas as pd
from scipy import stats
from statsmodels.stats.proportion import proportions_ztest

## How to Identify Null and Alternative Hypotheses

### Two Golden Rules

Before diving into examples, there are two fundamental rules about hypotheses that you must always remember:

**Rule 1: The null hypothesis always contains the equality sign.**

The null hypothesis ($H_0$) must always include an equality sign. This could be $=$ , $\leq$ , or $\geq$ . The alternative hypothesis ($H_1$ or $H_a$) will then contain the opposite sign ($\neq$ , $>$ , or $<$ respectively).

**Rule 2: The null and alternative hypotheses must be mutually exclusive and collectively exhaustive.**

This means two things:
- They cannot overlap (mutually exclusive). The parameter cannot satisfy both $H_0$ and $H_1$ simultaneously.
- Together, they must cover all possible values of the parameter (collectively exhaustive). There is no third option.

### Step-by-Step Framework for Identifying Hypotheses

Many people make the common mistake of always putting their research question into the alternative hypothesis. To avoid this confusion, follow these steps:

**Step 1: Write down the research question in mathematical notation.**
Translate the research question into a mathematical statement about the population parameter.

**Step 2: Write down the opposite of the research question.**
Identify the complement of the research question. This is the logical opposite that covers all other possible values.

**Step 3: Check which one contains the equality sign.**
Among the research question and its opposite, identify which one has an equality sign ($=$ , $\leq$ , or $\geq$ ). This one becomes your null hypothesis.

**Step 4: The remaining statement becomes your alternative hypothesis.**
The other statement (with the strict inequality: $\neq$ , $>$ , or $<$ ) becomes your alternative hypothesis.

**Step 5: Run the test and make a decision.**
After conducting the test, either:
- Reject $H_0$ , or
- Fail to reject $H_0$

**Step 6: Interpret the result.**
If $H_0$ is rejected, the data supports the alternative hypothesis. If $H_0$ is not rejected, we conclude that there is not enough evidence against $H_0$, and it remains plausible.

---

### Examples

**Example 1**

A company claims that the average salary of its employees is exactly 50 million Tomans.

<details>
<summary>Solution (Click to reveal)</summary>

**Step 1: Write the research question:** $\mu = 50$

**Step 2: Opposite:** $\mu \neq 50$

**Step 3: Which contains equality?** The research question itself ($\mu = 50$) contains the equality sign.

**Step 4: Hypotheses:**
- $H_0: \mu = 50$
- $H_1: \mu \neq 50$

**Step 5:** Run the test.

**Step 6:** If $H_0$ is rejected, we conclude the average salary is not 50 million. If not rejected, we say there is no evidence that the average salary differs from 50 million.

</details>

---

**Example 2**

A store owner believes that the average monthly revenue has increased and is now more than 200 million Tomans.

<details>
<summary>Solution (Click to reveal)</summary>

**Step 1: Write the research question:** $\mu > 200$

**Step 2: Opposite:** $\mu \leq 200$

**Step 3: Which contains equality?** The opposite ($\mu \leq 200$) contains the equality sign.

**Step 4: Hypotheses:**
- $H_0: \mu \leq 200$
- $H_1: \mu > 200$

**Step 5:** Run the test.

**Step 6:** If $H_0$ is rejected, we conclude the average revenue is more than 200 million. If not rejected, we say there is no evidence that revenue has increased above 200 million.

</details>

---

**Example 3**

A factory manager claims that the average production time for each unit is less than 30 minutes.

<details>
<summary>Solution (Click to reveal)</summary>

**Step 1: Write the research question:** $\mu < 30$

**Step 2: Opposite:** $\mu \geq 30$

**Step 3: Which contains equality?** The opposite ($\mu \geq 30$) contains the equality sign.

**Step 4: Hypotheses:**
- $H_0: \mu \geq 30$
- $H_1: \mu < 30$

**Step 5:** Run the test.

**Step 6:** If $H_0$ is rejected, we conclude the average production time is less than 30 minutes. If not rejected, we say there is no evidence that production time is below 30 minutes.

</details>

---

**Example 4**

An analyst wants to know if the average customer satisfaction score for male customers differs from female customers.

<details>
<summary>Solution (Click to reveal)</summary>

**Step 1: Write the research question:** $\mu_{\text{male}} \neq \mu_{\text{female}}$

**Step 2: Opposite:** $\mu_{\text{male}} = \mu_{\text{female}}$

**Step 3: Which contains equality?** The opposite contains the equality sign.

**Step 4: Hypotheses:**
- $H_0: \mu_{\text{male}} = \mu_{\text{female}}$
- $H_1: \mu_{\text{male}} \neq \mu_{\text{female}}$

**Step 5:** Run the test.

**Step 6:** If $H_0$ is rejected, we conclude satisfaction scores differ between genders. If not rejected, we say there is no evidence of a difference.

</details>

---

**Example 5**

A fitness center claims that their program helps participants lose at least 5 kg on average.

<details>
<summary>Solution (Click to reveal)</summary>

**Step 1: Write the research question:** $\mu \geq 5$

**Step 2: Opposite:** $\mu < 5$

**Step 3: Which contains equality?** The research question ($\mu \geq 5$) contains the equality sign.

**Step 4: Hypotheses:**
- $H_0: \mu \geq 5$
- $H_1: \mu < 5$

**Step 5:** Run the test.

**Step 6:** If $H_0$ is rejected, we conclude average weight loss is less than 5 kg. If not rejected, we say there is no evidence that weight loss falls below 5 kg.

</details>

---

**Example 6**

A courier company claims that the average delivery time is at most 45 minutes.

<details>
<summary>Solution (Click to reveal)</summary>

**Step 1: Write the research question:** $\mu \leq 45$

**Step 2: Opposite:** $\mu > 45$

**Step 3: Which contains equality?** The research question ($\mu \leq 45$) contains the equality sign.

**Step 4: Hypotheses:**
- $H_0: \mu \leq 45$
- $H_1: \mu > 45$

**Step 5:** Run the test.

**Step 6:** If $H_0$ is rejected, we conclude the average delivery time exceeds 45 minutes. If not rejected, we say there is no evidence that delivery time is above 45 minutes.

</details>

---

**Example 7**

A researcher wants to know if the average weight of men is different from the average weight of women.

<details>
<summary>Solution (Click to reveal)</summary>

**Step 1: Write the research question:** $\mu_{\text{men}} \neq \mu_{\text{women}}$

**Step 2: Opposite:** $\mu_{\text{men}} = \mu_{\text{women}}$

**Step 3: Which contains equality?** The opposite contains the equality sign.

**Step 4: Hypotheses:**
- $H_0: \mu_{\text{men}} = \mu_{\text{women}}$
- $H_1: \mu_{\text{men}} \neq \mu_{\text{women}}$

**Step 5:** Run the test.

**Step 6:** If $H_0$ is rejected, we conclude the average weight differs between men and women. If not rejected, we say there is no evidence of a difference.

</details>

---

**Example 8**

A company wants to test whether the average customer satisfaction score of their new product is higher than the old product.

<details>
<summary>Solution (Click to reveal)</summary>

**Step 1: Write the research question:** $\mu_{\text{new}} > \mu_{\text{old}}$

**Step 2: Opposite:** $\mu_{\text{new}} \leq \mu_{\text{old}}$

**Step 3: Which contains equality?** The opposite ($\mu_{\text{new}} \leq \mu_{\text{old}}$) contains the equality sign.

**Step 4: Hypotheses:**
- $H_0: \mu_{\text{new}} \leq \mu_{\text{old}}$
- $H_1: \mu_{\text{new}} > \mu_{\text{old}}$

**Step 5:** Run the test.

**Step 6:** If $H_0$ is rejected, we conclude the new product has higher satisfaction. If not rejected, we say there is no evidence that the new product performs better.

</details>

---

**Example 9**

A researcher claims that employees in the marketing department have at least the same average salary as employees in the finance department.

<details>
<summary>Solution (Click to reveal)</summary>

**Step 1: Write the research question:** $\mu_{\text{marketing}} \geq \mu_{\text{finance}}$

**Step 2: Opposite:** $\mu_{\text{marketing}} < \mu_{\text{finance}}$

**Step 3: Which contains equality?** The research question ($\mu_{\text{marketing}} \geq \mu_{\text{finance}}$) contains the equality sign.

**Step 4: Hypotheses:**
- $H_0: \mu_{\text{marketing}} \geq \mu_{\text{finance}}$
- $H_1: \mu_{\text{marketing}} < \mu_{\text{finance}}$

**Step 5:** Run the test.

**Step 6:** If $H_0$ is rejected, we conclude marketing employees have lower average salary than finance employees. If not rejected, we say there is no evidence that marketing salaries are lower.

</details>

---

**Example 10**

A company claims that the average delivery time of their new courier service is at most the same as their old service.

<details>
<summary>Solution (Click to reveal)</summary>

**Step 1: Write the research question:** $\mu_{\text{new}} \leq \mu_{\text{old}}$

**Step 2: Opposite:** $\mu_{\text{new}} > \mu_{\text{old}}$

**Step 3: Which contains equality?** The research question ($\mu_{\text{new}} \leq \mu_{\text{old}}$) contains the equality sign.

**Step 4: Hypotheses:**
- $H_0: \mu_{\text{new}} \leq \mu_{\text{old}}$
- $H_1: \mu_{\text{new}} > \mu_{\text{old}}$

**Step 5:** Run the test.

**Step 6:** If $H_0$ is rejected, we conclude the new service has longer delivery time. If not rejected, we say there is no evidence that the new service is slower.

</details>

## One-Sample t-Test

This test comes in handy when we have a continuous numeric column and a specific number has been proposed for its mean. We want to see whether this proposal is correct or not.

For example, suppose a beverage company says the average volume of their bottles is 250 ml. We take a sample of bottles, measure their volumes, and want to see whether this statement is acceptable or if the difference we see between the sample mean and 250 is large enough to say the statement is wrong.

Before going to this test, we need to check the normality of the data. If the data are not normal, it is better to use non-parametric alternatives.

In [2]:
df = pd.read_csv('bottle_volumes.csv')
data = df['volume']
df

     volume
0     254.5
1     251.3
2     255.2
3     259.6
4     250.8
..      ...
145   255.9
146   245.8
147   245.4
148   254.6
149   253.5

[150 rows x 1 columns]

In [3]:
# Shapiro-Wilk test for normality
# h0: normal
# ha: not normal
shapiro_stat, shapiro_p = stats.shapiro(data)

print("Shapiro-Wilk Normality Test:")
print(f"p-value: {shapiro_p:.4f}")
print()

Shapiro-Wilk Normality Test:
p-value: 0.9425

**Case 1: We are told that the mean is exactly 250.**

<details>
<summary>Solution (Click to reveal)</summary>

**Step 1:** μ = 250  
**Step 2:** μ ≠ 250  
**Step 3:** The research question (μ = 250) contains the equality sign.  
**Step 4:**  
- H0: μ = 250  
- H1: μ ≠ 250

**Step 5:** Run the test.  
**Step 6:** If H0 is rejected, we conclude the mean is not 250. If not rejected, we say there is no evidence that the mean differs from 250.

</details>

In [4]:
# One-Sample t-Test
# Important parameters for stats.ttest_1samp:
# - a: sample data
# - popmean: the value we are comparing against (μ0)
# - alternative: direction of the alternative hypothesis
#                'two-sided' : μ ≠ μ0
#                'greater'   : μ > μ0
#                'less'      : μ < μ0
# Returns: t-statistic, p-value

In [5]:
# Case 1: Two-sided
t_stat, p_value = stats.ttest_1samp(data, 250, alternative='two-sided')
print("Case 1 - H0: μ = 250, H1: μ ≠ 250")
print(f"p-value: {p_value:.4f}")
print("Reject H0" if p_value < 0.05 else "Fail to reject H0")
print()

Case 1 - H0: μ = 250, H1: μ ≠ 250
p-value: 0.0001
Reject H0

**Case 2: We are told that the mean is more than 250.**

<details>
<summary>Solution (Click to reveal)</summary>

**Step 1:** μ > 250  
**Step 2:** μ ≤ 250  
**Step 3:** The opposite (μ ≤ 250) contains the equality sign.  
**Step 4:**  
- H0: μ ≤ 250  
- H1: μ > 250  

**Step 5:** Run the test.  
**Step 6:** If H0 is rejected, we conclude the mean is more than 250. If not rejected, we say there is no evidence that the mean exceeds 250.

</details>

In [6]:
# Case 2: Right-tailed (greater)
t_stat, p_value = stats.ttest_1samp(data, 250, alternative='greater')
print("Case 2 - H0: μ ≤ 250, H1: μ > 250")
print(f"p-value: {p_value:.4f}")
print("Reject H0" if p_value < 0.05 else "Fail to reject H0")
print()

Case 2 - H0: μ ≤ 250, H1: μ > 250
p-value: 0.0000
Reject H0

**Case 3: We are told that the mean is less than 250.**

<details>
<summary>Solution (Click to reveal)</summary>

**Step 1:** μ < 250  
**Step 2:** μ ≥ 250  
**Step 3:** The opposite (μ ≥ 250) contains the equality sign.  
**Step 4:**  
- H0: μ ≥ 250  
- H1: μ < 250

**Step 5:** Run the test.  
**Step 6:** If H0 is rejected, we conclude the mean is less than 250. If not rejected, we say there is no evidence that the mean is below 250.

</details>

In [7]:
# Case 3: Left-tailed (less)
t_stat, p_value = stats.ttest_1samp(data, 250, alternative='less')
print("Case 3 - H0: μ ≥ 250, H1: μ < 250")
print(f"p-value: {p_value:.4f}")
print("Reject H0" if p_value < 0.05 else "Fail to reject H0")
print()

Case 3 - H0: μ ≥ 250, H1: μ < 250
p-value: 1.0000
Fail to reject H0

**Case 4: We are told that the mean is at least 250.**

<details>
<summary>Solution (Click to reveal)</summary>

**Step 1:** μ ≥ 250  
**Step 2:** μ < 250  
**Step 3:** The research question (μ ≥ 250) contains the equality sign.  
**Step 4:**  
- H0: μ ≥ 250  
- H1: μ < 250

**Step 5:** Run the test.  
**Step 6:** If H0 is rejected, we conclude the mean is less than 250. If not rejected, we say there is no evidence that the mean falls below 250.

</details>

In [8]:
# Case 4: Same as Case 3 (at least)
t_stat, p_value = stats.ttest_1samp(data, 250, alternative='less')
print("Case 4 - H0: μ ≥ 250, H1: μ < 250")
print(f"p-value: {p_value:.4f}")
print("Reject H0" if p_value < 0.05 else "Fail to reject H0")
print()

Case 4 - H0: μ ≥ 250, H1: μ < 250
p-value: 1.0000
Fail to reject H0

**Case 5: We are told that the mean is at most 250.**

<details>
<summary>Solution (Click to reveal)</summary>

**Step 1:** μ ≤ 250  
**Step 2:** μ > 250  
**Step 3:** The research question (μ ≤ 250) contains the equality sign.  
**Step 4:**  
- H0: μ ≤ 250  
- H1: μ > 250

**Step 5:** Run the test.  
**Step 6:** If H0 is rejected, we conclude the mean is more than 250. If not rejected, we say there is no evidence that the mean exceeds 250.

</details>

In [9]:
# Case 5: Same as Case 2 (at most)
t_stat, p_value = stats.ttest_1samp(data, 250, alternative='greater')
print("Case 5 - H0: μ ≤ 250, H1: μ > 250")
print(f"p-value: {p_value:.4f}")
print("Reject H0" if p_value < 0.05 else "Fail to reject H0")

Case 5 - H0: μ ≤ 250, H1: μ > 250
p-value: 0.0000
Reject H0

As you can see, following the steps we learned for identifying hypotheses, Case 4 looks the same as Case 3, and Case 5 looks the same as Case 2. We determine the hypotheses according to what we learned. Then we run the test and calculate the p-value. The p-value tells us whether we should reject the null hypothesis or not. After that, we check our original question and see whether it matches the result or not.

## Two-Sample t-Test

This test comes in handy when we have a continuous numeric column and we want to compare the means of two independent groups. We want to see whether the difference we see between the two sample means is large enough to say there is a real difference between the two populations.

For example, suppose we want to compare the average salary of male and female employees in a company. We take a sample of salaries from each group and want to see whether the difference we see is meaningful or just due to random sampling.

Before going to this test, we need to check the normality of the data in each group. If the data are not normal, it is better to use non-parametric alternatives.

In [10]:
df = pd.read_csv('salary_data.csv')
df.head()

   salary gender
0    60.0   Male
1    53.6   Male
2    61.5   Male
3    70.2   Male
4    52.7   Male

In [11]:
male = df[df['gender'] == 'Male']['salary']      # Male group (left side in hypotheses)
female = df[df['gender'] == 'Female']['salary']  # Female group (right side in hypotheses)

In [12]:
# Shapiro-Wilk test for normality
shapiro_stat1, shapiro_p1 = stats.shapiro(male)
shapiro_stat2, shapiro_p2 = stats.shapiro(female)

print("Shapiro-Wilk Normality Test:")
print(f"Male - p-value: {shapiro_p1:.4f}")
print(f"Female - p-value: {shapiro_p2:.4f}")
print()

Shapiro-Wilk Normality Test:
Male - p-value: 0.6526
Female - p-value: 0.0860

**Case 1: We are told that the two means are equal.**

<details>
<summary>Solution (Click to reveal)</summary>

**Step 1:** μ_Male = μ_Female  
**Step 2:** μ_Male ≠ μ_Female  
**Step 3:** The research question (μ_Male = μ_Female) contains the equality sign.  
**Step 4:**  
- H0: μ_Male = μ_Female  
- H1: μ_Male ≠ μ_Female

**Step 5:** Run the test.  
**Step 6:** If H0 is rejected, we conclude the means are different. If not rejected, we say there is no evidence of a difference between the two groups.

</details>

In [13]:
# Two-Sample t-Test
# Important parameters for stats.ttest_ind:
# - a: first sample (Male - left side in hypotheses)
# - b: second sample (Female - right side in hypotheses)
# - equal_var: True for standard t-test (equal variances assumed)
#              False for Welch's t-test (unequal variances)
# - alternative: direction of the alternative hypothesis
#                'two-sided' : μ_Male ≠ μ_Female
#                'greater'   : μ_Male > μ_Female
#                'less'      : μ_Male < μ_Female
# Returns: t-statistic, p-value

In [14]:
# Case 1: Two-sided
t_stat, p_value = stats.ttest_ind(male, female, equal_var=False, alternative='two-sided')
print("Case 1 - H0: μ_Male = μ_Female, H1: μ_Male ≠ μ_Female")
print(f"p-value: {p_value:.4f}")
print("Reject H0" if p_value < 0.05 else "Fail to reject H0")
print()

Case 1 - H0: μ_Male = μ_Female, H1: μ_Male ≠ μ_Female
p-value: 0.0050
Reject H0

**Case 2: We are told that mean of Male is more than Female.**

<details>
<summary>Solution (Click to reveal)</summary>

**Step 1:** μ_Male > μ_Female  
**Step 2:** μ_Male ≤ μ_Female  
**Step 3:** The opposite (μ_Male ≤ μ_Female) contains the equality sign.  
**Step 4:**  
- H0: μ_Male ≤ μ_Female  
- H1: μ_Male > μ_Female  

**Step 5:** Run the test.  
**Step 6:** If H0 is rejected, we conclude males have higher mean salary. If not rejected, we say there is no evidence that males earn more.

</details>

In [15]:
# Case 2: Right-tailed (greater)
t_stat, p_value = stats.ttest_ind(male, female, equal_var=False, alternative='greater')
print("Case 2 - H0: μ_Male ≤ μ_Female, H1: μ_Male > μ_Female")
print(f"p-value: {p_value:.4f}")
print("Reject H0" if p_value < 0.05 else "Fail to reject H0")
print()

Case 2 - H0: μ_Male ≤ μ_Female, H1: μ_Male > μ_Female
p-value: 0.0025
Reject H0

**Case 3: We are told that mean of Male is less than Female.**

<details>
<summary>Solution (Click to reveal)</summary>

**Step 1:** μ_Male < μ_Female  
**Step 2:** μ_Male ≥ μ_Female  
**Step 3:** The opposite (μ_Male ≥ μ_Female) contains the equality sign.  
**Step 4:**  
- H0: μ_Male ≥ μ_Female  
- H1: μ_Male < μ_Female

**Step 5:** Run the test.  
**Step 6:** If H0 is rejected, we conclude males have lower mean salary. If not rejected, we say there is no evidence that males earn less.

</details>

In [16]:
# Case 3: Left-tailed (less)
t_stat, p_value = stats.ttest_ind(male, female, equal_var=False, alternative='less')
print("Case 3 - H0: μ_Male ≥ μ_Female, H1: μ_Male < μ_Female")
print(f"p-value: {p_value:.4f}")
print("Reject H0" if p_value < 0.05 else "Fail to reject H0")
print()

Case 3 - H0: μ_Male ≥ μ_Female, H1: μ_Male < μ_Female
p-value: 0.9975
Fail to reject H0

**Case 4: We are told that mean of Male is at least as much as Female.**

<details>
<summary>Solution (Click to reveal)</summary>

**Step 1:** μ_Male ≥ μ_Female  
**Step 2:** μ_Male < μ_Female  
**Step 3:** The research question (μ_Male ≥ μ_Female) contains the equality sign.  
**Step 4:**  
- H0: μ_Male ≥ μ_Female  
- H1: μ_Male < μ_Female  

**Step 5:** Run the test.  
**Step 6:** If H0 is rejected, we conclude males have lower mean salary. If not rejected, we say there is no evidence that males earn less than females.

</details>

In [17]:
# Case 4: Same as Case 3 (at least)
t_stat, p_value = stats.ttest_ind(male, female, equal_var=False, alternative='less')
print("Case 4 - H0: μ_Male ≥ μ_Female, H1: μ_Male < μ_Female")
print(f"p-value: {p_value:.4f}")
print("Reject H0" if p_value < 0.05 else "Fail to reject H0")
print()

Case 4 - H0: μ_Male ≥ μ_Female, H1: μ_Male < μ_Female
p-value: 0.9975
Fail to reject H0

**Case 5: We are told that mean of Male is at most as much as Female.**

<details>
<summary>Solution (Click to reveal)</summary>

**Step 1:** μ_Male ≤ μ_Female  
**Step 2:** μ_Male > μ_Female  
**Step 3:** The research question (μ_Male ≤ μ_Female) contains the equality sign.  
**Step 4:**  
- H0: μ_Male ≤ μ_Female  
- H1: μ_Male > μ_Female  

**Step 5:** Run the test.  
**Step 6:** If H0 is rejected, we conclude males have higher mean salary. If not rejected, we say there is no evidence that males earn more than females.

</details>

In [18]:
# Case 5: Same as Case 2 (at most)
t_stat, p_value = stats.ttest_ind(male, female, equal_var=False, alternative='greater')
print("Case 5 - H0: μ_Male ≤ μ_Female, H1: μ_Male > μ_Female")
print(f"p-value: {p_value:.4f}")
print("Reject H0" if p_value < 0.05 else "Fail to reject H0")
print()

Case 5 - H0: μ_Male ≤ μ_Female, H1: μ_Male > μ_Female
p-value: 0.0025
Reject H0

As you can see, following the steps we learned for identifying hypotheses, Case 4 looks the same as Case 3, and Case 5 looks the same as Case 2. We determine the hypotheses according to what we learned. Then we run the test and calculate the p-value. The p-value tells us whether we should reject the null hypothesis or not. After that, we check our original question and see whether it matches the result or not.

## Mann-Whitney U Test

This test comes in handy when we have a continuous numeric column and we want to compare two independent groups, but the normality assumption for the t-test is violated. This is the non-parametric alternative to the two-sample t-test.

Instead of comparing means, this test compares the distributions of the two groups. It checks whether one group tends to have larger values than the other.

For example, suppose we want to compare the exam scores of students from two different professors. Exam scores are usually left-skewed because most students score high, but some score very low. We take a sample of scores from each professor's class and want to see whether there is a significant difference between them.

Before using this test, we check the normality of the data in each group. If the data are not normal (p-value from Shapiro-Wilk test is less than 0.05), we use this test instead of the t-test.

In [19]:
df = pd.read_csv('scores_data.csv')
df.head()

   score   professor
0   85.9  Dr. Ahmadi
1   83.6  Dr. Ahmadi
2   81.8  Dr. Ahmadi
3   72.3  Dr. Ahmadi
4   97.5  Dr. Ahmadi

In [20]:
ahmadi_scores = df[df['professor'] == 'Dr. Ahmadi']['score']
karimi_scores = df[df['professor'] == 'Dr. Karimi']['score']

In [21]:
# Shapiro-Wilk test for normality
shapiro_stat1, shapiro_p1 = stats.shapiro(ahmadi_scores)
shapiro_stat2, shapiro_p2 = stats.shapiro(karimi_scores)

print("Shapiro-Wilk Normality Test:")
print(f"Dr. Ahmadi Scores - p-value: {shapiro_p1:.4f}")
print(f"Dr. Karimi Scores - p-value: {shapiro_p2:.4f}")
print()

Shapiro-Wilk Normality Test:
Dr. Ahmadi Scores - p-value: 0.0414
Dr. Karimi Scores - p-value: 0.0446

**Case 1: We are told that the two score distributions are equal.**

<details>
<summary>Solution (Click to reveal)</summary>

**Step 1:** Distribution of Dr. Ahmadi's scores = Distribution of Dr. Karimi's scores  
**Step 2:** Distribution of Dr. Ahmadi's scores ≠ Distribution of Dr. Karimi's scores  
**Step 3:** The research question contains the equality sign.  
**Step 4:**  
- H0: Distribution of Dr. Ahmadi's scores = Distribution of Dr. Karimi's scores  
- H1: Distribution of Dr. Ahmadi's scores ≠ Distribution of Dr. Karimi's scores

**Step 5:** Run the test.  
**Step 6:** If H0 is rejected, we conclude the distributions are different. If not rejected, we say there is no evidence of a difference between the two professors' score distributions.

</details>

In [22]:
# Mann-Whitney U Test
# Important parameters for stats.mannwhitneyu:
# - x: first sample (Dr. Ahmadi Scores - left side in hypotheses)
# - y: second sample (Dr. Karimi Scores - right side in hypotheses)
# - alternative: direction of the alternative hypothesis
#                'two-sided' : Distribution Ahmadi's scores ≠ Distribution Karimi's scores
#                'greater'   : Distribution Ahmadi's scores > Distribution Karimi's scores
#                'less'      : Distribution Ahmadi's scores < Distribution Karimi's scores
# Returns: U-statistic, p-value

In [23]:
# Case 1: Two-sided
u_stat, p_value = stats.mannwhitneyu(ahmadi_scores, karimi_scores, alternative='two-sided')
print("Case 1 - H0: Distribution Ahmadi's scores = Distribution Karimi's scores, H1: Distribution Ahmadi's scores ≠ Distribution Karimi's scores")
print(f"p-value: {p_value:.4f}")
print("Reject H0" if p_value < 0.05 else "Fail to reject H0")
print()

Case 1 - H0: Distribution Ahmadi's scores = Distribution Karimi's scores, H1: Distribution Ahmadi's scores ≠ Distribution Karimi's scores
p-value: 0.0000
Reject H0

**Case 2: We are told that Dr. Ahmadi's students have higher scores than Dr. Karimi's students.**

<details>
<summary>Solution (Click to reveal)</summary>

**Step 1:** Distribution of Dr. Ahmadi's scores > Distribution of Dr. Karimi's scores  
**Step 2:** Distribution of Dr. Ahmadi's scores ≤ Distribution of Dr. Karimi's scores  
**Step 3:** The opposite contains the equality sign.  
**Step 4:**  
- H0: Distribution of Dr. Ahmadi's scores ≤ Distribution of Dr. Karimi's scores  
- H1: Distribution of Dr. Ahmadi's scores > Distribution of Dr. Karimi's scores

**Step 5:** Run the test.  
**Step 6:** If H0 is rejected, we conclude Dr. Ahmadi's students have higher scores. If not rejected, we say there is no evidence that Dr. Ahmadi's students score higher.

</details>

In [24]:
# Case 2: Right-tailed (greater)
u_stat, p_value = stats.mannwhitneyu(ahmadi_scores, karimi_scores, alternative='greater')
print("Case 2 - H0: Distribution Ahmadi's scores ≤ Distribution Karimi's scores, H1: Distribution Ahmadi's scores > Distribution Karimi's scores")
print(f"p-value: {p_value:.4f}")
print("Reject H0" if p_value < 0.05 else "Fail to reject H0")
print()

Case 2 - H0: Distribution Ahmadi's scores ≤ Distribution Karimi's scores, H1: Distribution Ahmadi's scores > Distribution Karimi's scores
p-value: 0.0000
Reject H0

**Case 3: We are told that Dr. Ahmadi's students have lower scores than Dr. Karimi's students.**

<details>
<summary>Solution (Click to reveal)</summary>

**Step 1:** Distribution of Dr. Ahmadi's scores < Distribution of Dr. Karimi's scores  
**Step 2:** Distribution of Dr. Ahmadi's scores ≥ Distribution of Dr. Karimi's scores  
**Step 3:** The opposite contains the equality sign.  
**Step 4:**  
- H0: Distribution of Dr. Ahmadi's scores ≥ Distribution of Dr. Karimi's scores  
- H1: Distribution of Dr. Ahmadi's scores < Distribution of Dr. Karimi's scores

**Step 5:** Run the test.  
**Step 6:** If H0 is rejected, we conclude Dr. Ahmadi's students have lower scores. If not rejected, we say there is no evidence that Dr. Ahmadi's students score lower.

</details>

In [25]:
# Case 3: Left-tailed (less)
u_stat, p_value = stats.mannwhitneyu(ahmadi_scores, karimi_scores, alternative='less')
print("Case 3 - H0: Distribution Ahmadi's scores ≥ Distribution Karimi's scores, H1: Distribution Ahmadi's scores < Distribution Karimi's scores")
print(f"p-value: {p_value:.4f}")
print("Reject H0" if p_value < 0.05 else "Fail to reject H0")
print()

Case 3 - H0: Distribution Ahmadi's scores ≥ Distribution Karimi's scores, H1: Distribution Ahmadi's scores < Distribution Karimi's scores
p-value: 1.0000
Fail to reject H0

**Case 4: We are told that Dr. Ahmadi's students' scores are at least as high as Dr. Karimi's students.**

<details>
<summary>Solution (Click to reveal)</summary>

**Step 1:** Distribution of Dr. Ahmadi's scores ≥ Distribution of Dr. Karimi's scores  
**Step 2:** Distribution of Dr. Ahmadi's scores < Distribution of Dr. Karimi's scores  
**Step 3:** The research question contains the equality sign.  
**Step 4:**  
- H0: Distribution of Dr. Ahmadi's scores ≥ Distribution of Dr. Karimi's scores  
- H1: Distribution of Dr. Ahmadi's scores < Distribution of Dr. Karimi's scores

**Step 5:** Run the test.  
**Step 6:** If H0 is rejected, we conclude Dr. Ahmadi's students have lower scores. If not rejected, we say there is no evidence that Dr. Ahmadi's students score lower than Dr. Karimi's students.

</details>

In [26]:
# Case 4: Same as Case 3 (at least)
u_stat, p_value = stats.mannwhitneyu(ahmadi_scores, karimi_scores, alternative='less')
print("Case 4 - H0: Distribution Ahmadi's scores ≥ Distribution Karimi's scores, H1: Distribution Ahmadi's scores < Distribution Karimi's scores")
print(f"p-value: {p_value:.4f}")
print("Reject H0" if p_value < 0.05 else "Fail to reject H0")
print()

Case 4 - H0: Distribution Ahmadi's scores ≥ Distribution Karimi's scores, H1: Distribution Ahmadi's scores < Distribution Karimi's scores
p-value: 1.0000
Fail to reject H0

**Case 5: We are told that Dr. Ahmadi's students' scores are at most as high as Dr. Karimi's students.**

<details>
<summary>Solution (Click to reveal)</summary>

**Step 1:** Distribution of Dr. Ahmadi's scores ≤ Distribution of Dr. Karimi's scores  
**Step 2:** Distribution of Dr. Ahmadi's scores > Distribution of Dr. Karimi's scores  
**Step 3:** The research question contains the equality sign.  
**Step 4:**  
- H0: Distribution of Dr. Ahmadi's scores ≤ Distribution of Dr. Karimi's scores  
- H1: Distribution of Dr. Ahmadi's scores > Distribution of Dr. Karimi's scores  
**Step 5:** Run the test.  
**Step 6:** If H0 is rejected, we conclude Dr. Ahmadi's students have higher scores. If not rejected, we say there is no evidence that Dr. Ahmadi's students score higher than Dr. Karimi's students.

</details>

In [27]:
# Case 5: Same as Case 2 (at most)
u_stat, p_value = stats.mannwhitneyu(ahmadi_scores, karimi_scores, alternative='greater')
print("Case 5 - H0: Distribution Ahmadi's scores ≤ Distribution Karimi's scores, H1: Distribution Ahmadi's scores > Distribution Karimi's scores")
print(f"p-value: {p_value:.4f}")
print("Reject H0" if p_value < 0.05 else "Fail to reject H0")

Case 5 - H0: Distribution Ahmadi's scores ≤ Distribution Karimi's scores, H1: Distribution Ahmadi's scores > Distribution Karimi's scores
p-value: 0.0000
Reject H0

As you can see, following the steps we learned for identifying hypotheses, Case 4 looks the same as Case 3, and Case 5 looks the same as Case 2. We determine the hypotheses according to what we learned. Then we run the test and calculate the p-value. The p-value tells us whether we should reject the null hypothesis or not. After that, we check our original question and see whether it matches the result or not.

## One-Sample Proportion Test

This test comes in handy when we have a binary column and we want to compare the proportion of successes in our sample against a known or claimed proportion. For example, suppose a company claims that 60% of their customers are satisfied, but we think the actual proportion is different.

We take a sample of 200 customers and find that 100 of them are satisfied (50%). We want to see whether the difference between our sample proportion (50%) and the claimed proportion (60%) is large enough to say the company's claim is wrong.

Before using this test, we need to check whether we can use the normal approximation. As a rule of thumb, if the sample size is large enough (at least 30), the sampling distribution of the proportion will be approximately normal, thanks to the Central Limit Theorem. A more precise condition is that n * p ≥ 5 and n * (1-p) ≥ 5.

In [28]:
df = pd.read_csv('satisfaction_data.csv')
df

     customer_id   satisfaction
0              1      Satisfied
1              2  Not Satisfied
2              3  Not Satisfied
3              4  Not Satisfied
4              5      Satisfied
..           ...            ...
195          196      Satisfied
196          197  Not Satisfied
197          198  Not Satisfied
198          199  Not Satisfied
199          200  Not Satisfied

[200 rows x 2 columns]

In [29]:
# Calculate observed proportion
n = len(df)
successes = (df['satisfaction'] == 'Satisfied').sum()
p_hat = successes / n

print(f"Sample size: {n}")
print(f"Number satisfied: {successes}")
print(f"Sample proportion: {p_hat:.3f}")
print()

# Check conditions for normal approximation
print("Checking conditions for normal approximation:")
print(f"n*p = {n * p_hat:.1f}")
print(f"n*(1-p) = {n * (1-p_hat):.1f}")
print()

if n * p_hat >= 5 and n * (1-p_hat) >= 5:
    print("Conditions are met. Normal approximation is valid.")
else:
    print("Conditions are not met.")

Sample size: 200
Number satisfied: 108
Sample proportion: 0.540

Checking conditions for normal approximation:
n*p = 108.0
n*(1-p) = 92.0

Conditions are met. Normal approximation is valid.

**Case 1: We are told that the proportion is exactly 0.60.**

<details>
<summary>Solution (Click to reveal)</summary>

**Step 1:** p = 0.60  
**Step 2:** p ≠ 0.60  
**Step 3:** The research question (p = 0.60) contains the equality sign.  
**Step 4:**  
- H0: p = 0.60  
- H1: p ≠ 0.60

**Step 5:** Run the test.  
**Step 6:** If H0 is rejected, we conclude the proportion is not 0.60. If not rejected, we say there is no evidence that the proportion differs from 0.60.

</details>

In [30]:
# One-Sample Proportion Z-Test
# Important parameters for proportions_ztest:
# - count: number of successes
# - nobs: total number of observations (sample size)
# - value: proportion under the null hypothesis (p0)
# - alternative: direction of the alternative hypothesis
#                'two-sided' : p ≠ p0
#                'larger'    : p > p0
#                'smaller'   : p < p0
# Returns: z-statistic, p-value

In [31]:
# Case 1: Two-sided
z_stat, p_value = proportions_ztest(count=successes, nobs=n, value=0.60, alternative='two-sided')
print("Case 1 - H0: p = 0.60, H1: p ≠ 0.60")
print(f"z-statistic: {z_stat:.4f}")
print(f"p-value: {p_value:.4f}")
print("Reject H0" if p_value < 0.05 else "Fail to reject H0")
print()

Case 1 - H0: p = 0.60, H1: p ≠ 0.60
z-statistic: -1.7025
p-value: 0.0887
Fail to reject H0

**Case 2: We are told that the proportion is more than 0.60.**

<details>
<summary>Solution (Click to reveal)</summary>

**Step 1:** p > 0.60  
**Step 2:** p ≤ 0.60  
**Step 3:** The opposite (p ≤ 0.60) contains the equality sign.  
**Step 4:**  
- H0: p ≤ 0.60  
- H1: p > 0.60

**Step 5:** Run the test.  
**Step 6:** If H0 is rejected, we conclude the proportion is more than 0.60. If not rejected, we say there is no evidence that the proportion exceeds 0.60.

</details>

In [32]:
# Case 2: Right-tailed (larger)
z_stat, p_value = proportions_ztest(count=successes, nobs=n, value=0.60, alternative='larger')
print("Case 2 - H0: p ≤ 0.60, H1: p > 0.60")
print(f"z-statistic: {z_stat:.4f}")
print(f"p-value: {p_value:.4f}")
print("Reject H0" if p_value < 0.05 else "Fail to reject H0")
print()

Case 2 - H0: p ≤ 0.60, H1: p > 0.60
z-statistic: -1.7025
p-value: 0.9557
Fail to reject H0

**Case 3: We are told that the proportion is less than 0.60.**

<details>
<summary>Solution (Click to reveal)</summary>

**Step 1:** p < 0.60  
**Step 2:** p ≥ 0.60  
**Step 3:** The opposite (p ≥ 0.60) contains the equality sign.  
**Step 4:**  
- H0: p ≥ 0.60  
- H1: p < 0.60

**Step 5:** Run the test.  
**Step 6:** If H0 is rejected, we conclude the proportion is less than 0.60. If not rejected, we say there is no evidence that the proportion is below 0.60.

</details>

In [33]:
# Case 3: Left-tailed (smaller)
z_stat, p_value = proportions_ztest(count=successes, nobs=n, value=0.60, alternative='smaller')
print("Case 3 - H0: p ≥ 0.60, H1: p < 0.60")
print(f"z-statistic: {z_stat:.4f}")
print(f"p-value: {p_value:.4f}")
print("Reject H0" if p_value < 0.05 else "Fail to reject H0")
print()

Case 3 - H0: p ≥ 0.60, H1: p < 0.60
z-statistic: -1.7025
p-value: 0.0443
Reject H0

**Case 4: We are told that the proportion is at least 0.60.**

<details>
<summary>Solution (Click to reveal)</summary>

**Step 1:** p ≥ 0.60  
**Step 2:** p < 0.60  
**Step 3:** The research question (p ≥ 0.60) contains the equality sign.  
**Step 4:**  
- H0: p ≥ 0.60  
- H1: p < 0.60  

**Step 5:** Run the test.  
**Step 6:** If H0 is rejected, we conclude the proportion is less than 0.60. If not rejected, we say there is no evidence that the proportion falls below 0.60.

</details>

In [34]:
# Case 4: Same as Case 3 (at least)
z_stat, p_value = proportions_ztest(count=successes, nobs=n, value=0.60, alternative='smaller')
print("Case 4 - H0: p ≥ 0.60, H1: p < 0.60")
print(f"z-statistic: {z_stat:.4f}")
print(f"p-value: {p_value:.4f}")
print("Reject H0" if p_value < 0.05 else "Fail to reject H0")
print()

Case 4 - H0: p ≥ 0.60, H1: p < 0.60
z-statistic: -1.7025
p-value: 0.0443
Reject H0

**Case 5: We are told that the proportion is at most 0.60.**

<details>
<summary>Solution (Click to reveal)</summary>

**Step 1:** p ≤ 0.60  
**Step 2:** p > 0.60  
**Step 3:** The research question (p ≤ 0.60) contains the equality sign.  
**Step 4:**  
- H0: p ≤ 0.60  
- H1: p > 0.60  

**Step 5:** Run the test.  
**Step 6:** If H0 is rejected, we conclude the proportion is more than 0.60. If not rejected, we say there is no evidence that the proportion exceeds 0.60.

</details>

In [35]:
# Case 5: Same as Case 2 (at most)
z_stat, p_value = proportions_ztest(count=successes, nobs=n, value=0.60, alternative='larger')
print("Case 5 - H0: p ≤ 0.60, H1: p > 0.60")
print(f"z-statistic: {z_stat:.4f}")
print(f"p-value: {p_value:.4f}")
print("Reject H0" if p_value < 0.05 else "Fail to reject H0")

Case 5 - H0: p ≤ 0.60, H1: p > 0.60
z-statistic: -1.7025
p-value: 0.9557
Fail to reject H0

As you can see, following the steps we learned for identifying hypotheses, Case 4 looks the same as Case 3, and Case 5 looks the same as Case 2. We determine the hypotheses according to what we learned. Then we run the test and calculate the p-value. The p-value tells us whether we should reject the null hypothesis or not. After that, we check our original question and see whether it matches the result or not.

## Two-Sample Proportion Test

This test comes in handy when we have a binary column and we want to compare the proportions of successes between two independent groups. For example, suppose we want to compare the satisfaction rates between male and female customers. We take a sample from each group and want to see whether there is a significant difference between the two proportions.

We take a sample of 150 male customers and find that 90 are satisfied (60%). We also take a sample of 150 female customers and find that 75 are satisfied (50%). We want to see whether the difference between these two proportions is large enough to say there is a real difference in satisfaction rates between genders.

Before using this test, we need to check whether we can use the normal approximation. The conditions are: n1 * p1 ≥ 5, n1 * (1-p1) ≥ 5, n2 * p2 ≥ 5, and n2 * (1-p2) ≥ 5.

In [36]:
df = pd.read_csv('satisfaction_gender_data.csv')
df.head()

   customer_id gender   satisfaction
0            1   Male      Satisfied
1            2   Male  Not Satisfied
2            3   Male  Not Satisfied
3            4   Male      Satisfied
4            5   Male      Satisfied

In [37]:
# Calculate successes for each group
male_success = len(df[(df['gender'] == 'Male') & (df['satisfaction'] == 'Satisfied')])
female_success = len(df[(df['gender'] == 'Female') & (df['satisfaction'] == 'Satisfied')])
n_male = len(df[df['gender'] == 'Male'])
n_female = len(df[df['gender'] == 'Female'])

p_male = male_success / n_male
p_female = female_success / n_female

print(f"Male: n={n_male}, success={male_success}, p={p_male:.3f}")
print(f"Female: n={n_female}, success={female_success}, p={p_female:.3f}")
print()
# Check conditions

print(f"Male: n*p = {n_male * p_male:.1f}, n*(1-p) = {n_male * (1-p_male):.1f}")
print(f"Female: n*p = {n_female * p_female:.1f}, n*(1-p) = {n_female * (1-p_female):.1f}")
print()

if (n_male * p_male >= 5 and n_male * (1-p_male) >= 5 and
    n_female * p_female >= 5 and n_female * (1-p_female) >= 5):
    print("Conditions are met.")
else:
    print("Conditions are not met.")

Male: n=200, success=122, p=0.610
Female: n=200, success=91, p=0.455

Male: n*p = 122.0, n*(1-p) = 78.0
Female: n*p = 91.0, n*(1-p) = 109.0

Conditions are met.

**Case 1: We are told that the two proportions are equal.**

<details>
<summary>Solution (Click to reveal)</summary>

**Step 1:** p_Male = p_Female  
**Step 2:** p_Male ≠ p_Female  
**Step 3:** The research question (p_Male = p_Female) contains the equality sign.  
**Step 4:**  
- H0: p_Male = p_Female  
- H1: p_Male ≠ p_Female

**Step 5:** Run the test.  
**Step 6:** If H0 is rejected, we conclude the proportions are different. If not rejected, we say there is no evidence of a difference between the two groups.

</details>

In [38]:
# Two-Sample Proportion Z-Test
# Important parameters for proportions_ztest:
# - count: number of successes in each group (list of two)
# - nobs: total number of observations in each group (list of two)
# - alternative: direction of the alternative hypothesis
#                'two-sided' : p1 ≠ p2
#                'larger'    : p1 > p2
#                'smaller'   : p1 < p2
# Returns: z-statistic, p-value

In [39]:
# Case 1: Two-sided
z_stat, p_value = proportions_ztest(count=[male_success, female_success], 
                                     nobs=[n_male, n_female], 
                                     alternative='two-sided')
print("Case 1 - H0: p_Male = p_Female, H1: p_Male ≠ p_Female")
print(f"z-statistic: {z_stat:.4f}")
print(f"p-value: {p_value:.4f}")
print("Reject H0" if p_value < 0.05 else "Fail to reject H0")
print()

Case 1 - H0: p_Male = p_Female, H1: p_Male ≠ p_Female
z-statistic: 3.1066
p-value: 0.0019
Reject H0

**Case 2: We are told that male satisfaction is higher than female satisfaction.**

<details>
<summary>Solution (Click to reveal)</summary>

**Step 1:** p_Male > p_Female  
**Step 2:** p_Male ≤ p_Female  
**Step 3:** The opposite (p_Male ≤ p_Female) contains the equality sign.  
**Step 4:**  
- H0: p_Male ≤ p_Female  
- H1: p_Male > p_Female

**Step 5:** Run the test.  
**Step 6:** If H0 is rejected, we conclude males have higher satisfaction. If not rejected, we say there is no evidence that males are more satisfied.

</details>

In [40]:
# Case 2: Right-tailed (larger)
z_stat, p_value = proportions_ztest(count=[male_success, female_success], 
                                     nobs=[n_male, n_female], 
                                     alternative='larger')
print("Case 2 - H0: p_Male ≤ p_Female, H1: p_Male > p_Female")
print(f"z-statistic: {z_stat:.4f}")
print(f"p-value: {p_value:.4f}")
print("Reject H0" if p_value < 0.05 else "Fail to reject H0")
print()

Case 2 - H0: p_Male ≤ p_Female, H1: p_Male > p_Female
z-statistic: 3.1066
p-value: 0.0009
Reject H0

**Case 3: We are told that male satisfaction is lower than female satisfaction.**

<details>
<summary>Solution (Click to reveal)</summary>

**Step 1:** p_Male < p_Female  
**Step 2:** p_Male ≥ p_Female  
**Step 3:** The opposite (p_Male ≥ p_Female) contains the equality sign.  
**Step 4:**  
- H0: p_Male ≥ p_Female  
- H1: p_Male < p_Female  

**Step 5:** Run the test.  
**Step 6:** If H0 is rejected, we conclude males have lower satisfaction. If not rejected, we say there is no evidence that males are less satisfied.

</details>

In [41]:
# Case 3: Left-tailed (smaller)
z_stat, p_value = proportions_ztest(count=[male_success, female_success], 
                                     nobs=[n_male, n_female], 
                                     alternative='smaller')
print("Case 3 - H0: p_Male ≥ p_Female, H1: p_Male < p_Female")
print(f"z-statistic: {z_stat:.4f}")
print(f"p-value: {p_value:.4f}")
print("Reject H0" if p_value < 0.05 else "Fail to reject H0")
print()

Case 3 - H0: p_Male ≥ p_Female, H1: p_Male < p_Female
z-statistic: 3.1066
p-value: 0.9991
Fail to reject H0

**Case 4: We are told that male satisfaction is at least as high as female satisfaction.**

<details>
<summary>Solution (Click to reveal)</summary>

**Step 1:** p_Male ≥ p_Female  
**Step 2:** p_Male < p_Female  
**Step 3:** The research question (p_Male ≥ p_Female) contains the equality sign.  
**Step 4:**  
- H0: p_Male ≥ p_Female  
- H1: p_Male < p_Female  

**Step 5:** Run the test.  
**Step 6:** If H0 is rejected, we conclude males have lower satisfaction. If not rejected, we say there is no evidence that males are less satisfied than females.

</details>

In [42]:
# Case 4: Same as Case 3 (at least)
z_stat, p_value = proportions_ztest(count=[male_success, female_success], 
                                     nobs=[n_male, n_female], 
                                     alternative='smaller')
print("Case 4 - H0: p_Male ≥ p_Female, H1: p_Male < p_Female")
print(f"z-statistic: {z_stat:.4f}")
print(f"p-value: {p_value:.4f}")
print("Reject H0" if p_value < 0.05 else "Fail to reject H0")
print()

Case 4 - H0: p_Male ≥ p_Female, H1: p_Male < p_Female
z-statistic: 3.1066
p-value: 0.9991
Fail to reject H0

**Case 5: We are told that male satisfaction is at most as high as female satisfaction.**

<details>
<summary>Solution (Click to reveal)</summary>

**Step 1:** p_Male ≤ p_Female  
**Step 2:** p_Male > p_Female  
**Step 3:** The research question (p_Male ≤ p_Female) contains the equality sign.  
**Step 4:**  
- H0: p_Male ≤ p_Female  
- H1: p_Male > p_Female  
    
**Step 5:** Run the test.  
**Step 6:** If H0 is rejected, we conclude males have higher satisfaction. If not rejected, we say there is no evidence that males are more satisfied than females.

</details>

In [43]:
# Case 5: Same as Case 2 (at most)
z_stat, p_value = proportions_ztest(count=[male_success, female_success], 
                                     nobs=[n_male, n_female], 
                                     alternative='larger')
print("Case 5 - H0: p_Male ≤ p_Female, H1: p_Male > p_Female")
print(f"z-statistic: {z_stat:.4f}")
print(f"p-value: {p_value:.4f}")
print("Reject H0" if p_value < 0.05 else "Fail to reject H0")

Case 5 - H0: p_Male ≤ p_Female, H1: p_Male > p_Female
z-statistic: 3.1066
p-value: 0.0009
Reject H0

## Chi-Square Goodness of Fit Test

This test comes in handy when we have a categorical column and we want to check whether the observed frequencies in different categories match an expected distribution.

For example, suppose a company wants to know if their customer acquisition channels are performing as expected. They have 5 channels: Organic Search, Social Media, Email Marketing, Referral, and Direct. They expect that 40% of their customers come from Organic Search, 25% from Social Media, 20% from Email Marketing, 10% from Referral, and 5% from Direct.

We take a sample of 500 customers and record which channel brought them in. We want to see whether the actual distribution matches the expected distribution or not.

**H0:** The observed frequencies match the expected frequencies (p_Organic = 0.40, p_Social = 0.25, p_Email = 0.20, p_Referral = 0.10, p_Direct = 0.05)

**H1:** The observed frequencies do NOT match the expected frequencies

Now let's implement this with a practical example.

In [44]:
df = pd.read_csv('channels_data.csv')
df.head(100)

    customer_id acquisition_date acquisition_channel  acquisition_cost
0             1       2024-01-01      Organic Search              72.8
1             2       2024-01-02              Direct              58.2
2             3       2024-01-03     Email Marketing              37.9
3             4       2024-01-04        Social Media              83.2
4             5       2024-01-05      Organic Search              71.6
..          ...              ...                 ...               ...
95           96       2024-04-05        Social Media              52.7
96           97       2024-04-06        Social Media              70.1
97           98       2024-04-07        Social Media              25.5
98           99       2024-04-08      Organic Search              27.3
99          100       2024-04-09      Organic Search              13.7

[100 rows x 4 columns]

In [45]:
df = pd.read_csv('channels_data.csv')
df.head()

   customer_id acquisition_date acquisition_channel  acquisition_cost
0            1       2024-01-01      Organic Search              72.8
1            2       2024-01-02              Direct              58.2
2            3       2024-01-03     Email Marketing              37.9
3            4       2024-01-04        Social Media              83.2
4            5       2024-01-05      Organic Search              71.6

In [46]:
observed = df['acquisition_channel'].value_counts()
observed = observed.reindex(['Direct', 'Email Marketing', 'Organic Search', 'Referral', 'Social Media'])

**Case 1: We are told that the observed frequencies match the expected distribution.**

<details>
<summary>Solution (Click to reveal)</summary>

**Step 1:** p_Organic = 0.40, p_Social = 0.25, p_Email = 0.20, p_Referral = 0.10, p_Direct = 0.05  
**Step 2:** At least one proportion is different from the expected values  
**Step 3:** The research question contains the equality sign.  
**Step 4:**  
- H0: The observed frequencies match the expected frequencies (p_Organic = 0.40, p_Social = 0.25, p_Email = 0.20, p_Referral = 0.10, p_Direct = 0.05)  
- H1: The observed frequencies do NOT match the expected frequencies

**Step 5:** Run the test.  
**Step 6:** If H0 is rejected, we conclude the distribution does not match the expected pattern. If not rejected, we say there is no evidence that the distribution differs from expectations.

</details>

In [47]:
expected_probs = [0.05, 0.20, 0.40, 0.10, 0.25]
expected_counts = [len(df) * p for p in expected_probs]

# Important parameters for stats.chisquare:
# - f_obs: observed frequencies
# - f_exp: expected frequencies
# Returns: chi-square statistic, p-value

chi2_stat, p_value = stats.chisquare(f_obs=observed, f_exp=expected_counts)


print(f"Chi-square statistic: {chi2_stat:.4f}")
print(f"p-value: {p_value:.4f}")
print("Reject H0" if p_value < 0.05 else "Fail to reject H0")

Chi-square statistic: 2.6250
p-value: 0.6224
Fail to reject H0

As you can see, both cases lead to the same hypotheses because the test is fundamentally about whether the observed frequencies match the expected distribution. We run the test and calculate the p-value. The p-value tells us whether we should reject the null hypothesis or not. After that, we check our original question and see whether it matches the result or not.

## Chi-Square Test of Independence

This test comes in handy when we have two categorical columns and we want to check whether they are independent of each other or there is a relationship between them. The data is typically presented in a contingency table.

For example, suppose a company wants to know whether customer acquisition channel is related to customer gender. They have two categorical variables: acquisition channel (Organic Search, Social Media, Email Marketing, Referral, Direct) and gender (Male, Female). We take a sample of 500 customers and record both variables for each customer.

We want to see whether the distribution of acquisition channels differs between male and female customers or not. If the distribution of channels is the same across genders, then the two variables are independent.

Now we write the hypotheses. Similar to the goodness of fit test, this test has two possible cases:

In [48]:
df = pd.read_csv('channel_gender_data.csv')
df.head()

   customer_id gender acquisition_channel
0            1   Male      Organic Search
1            2   Male              Direct
2            3   Male     Email Marketing
3            4   Male        Social Media
4            5   Male      Organic Search

**Case 1: We are told that the two variables are independent.**

<details>
<summary>Solution (Click to reveal)</summary>

**Step 1:** The distribution of acquisition channels is the same for Male and Female customers (p_Male = p_Female)  
**Step 2:** The distribution of acquisition channels differs between Male and Female customers (p_Male ≠ p_Female)  
**Step 3:** The research question contains the equality sign.  
**Step 4:**  
- H0: The distribution of acquisition channels is the same for Male and Female customers (gender and channel are independent)  
- H1: The distribution of acquisition channels differs between Male and Female customers (gender and channel are not independent)  
**Step 5:** Run the test.  
**Step 6:** If H0 is rejected, we conclude the variables are related. If not rejected, we say there is no evidence of a relationship between gender and acquisition channel.

</details>

In [49]:
contingency_table = pd.crosstab(df['acquisition_channel'], df['gender'])

# Important parameters for stats.chi2_contingency:
# - observed: contingency table
# Returns: chi-square statistic, p-value, degrees of freedom, expected frequencies

chi2_stat, p_value, dof, expected = stats.chi2_contingency(contingency_table)

print(f"Chi-square statistic: {chi2_stat:.4f}")
print(f"Degrees of freedom: {dof}")
print(f"p-value: {p_value:.4f}")
print("Reject H0" if p_value < 0.05 else "Fail to reject H0")

Chi-square statistic: 53.3660
Degrees of freedom: 4
p-value: 0.0000
Reject H0

## Summary: How to Choose the Right Test

| Data Type | Normality | Sample Structure | Test | Function |
|-----------|-----------|------------------|------|----------|
| Continuous (numeric, e.g., height, weight, time, salary) | Normal | One Sample | One-Sample t-Test | `scipy.stats.ttest_1samp` |
| Continuous (numeric, e.g., height, weight, time, salary) | Normal | Two Independent Samples | Two-Sample t-Test | `scipy.stats.ttest_ind` |
| Continuous (numeric, e.g., height, weight, time, salary) | Not Normal | Two Independent Samples | Mann-Whitney U Test | `scipy.stats.mannwhitneyu` |
| Binary (2 levels, e.g., success/failure, yes/no) | - | One Sample | One-Sample Proportion Test | `statsmodels.stats.proportion.proportions_ztest` |
| Binary (2 levels, e.g., success/failure, yes/no) | - | Two Independent Samples | Two-Sample Proportion Test | `statsmodels.stats.proportion.proportions_ztest` |
| Categorical (2+ levels, e.g., color, city, channel) | - | One Sample | Chi-Square Goodness of Fit | `scipy.stats.chisquare` |
| Categorical (2+ levels, e.g., color, city, channel) | - | One Sample (Two Variables) | Chi-Square Test of Independence | `scipy.stats.chi2_contingency` |

---

### Decision Flow

**Step 1: Identify Your Data Type**

**Continuous Data** (numeric values like height, weight, time, salary)

Check normality using Shapiro-Wilk test.

If data is normal:
- One sample (comparing to a specific value): One-Sample t-Test (`ttest_1samp`)
- Two independent samples (comparing two groups): Two-Sample t-Test (`ttest_ind`)

If data is not normal:
- Two independent samples: Mann-Whitney U Test (`mannwhitneyu`)

**Binary Data** (categorical with 2 levels like success/failure, yes/no, purchase/no purchase)

- One sample (comparing to a known proportion): One-Sample Proportion Test (`proportions_ztest`)
- Two independent samples (comparing proportions between groups): Two-Sample Proportion Test (`proportions_ztest`)

**Categorical Data** (nominal with 2+ levels like color, city, channel)

- One variable (checking distribution across categories): Chi-Square Goodness of Fit (`chisquare`)
- Two variables (checking relationship between them): Chi-Square Test of Independence (`chi2_contingency`)

---

### Quick Reference

| Question | Test | Function |
|----------|------|----------|
| Is the mean equal to a specific value? (Normal data) | One-Sample t-Test | `ttest_1samp` |
| Are the means of two groups equal? (Normal data) | Two-Sample t-Test | `ttest_ind` |
| Are the distributions of two groups equal? (Not normal) | Mann-Whitney U Test | `mannwhitneyu` |
| Is the proportion equal to a specific value? | One-Sample Proportion Test | `proportions_ztest` |
| Are the proportions of two groups equal? | Two-Sample Proportion Test | `proportions_ztest` |
| Does the distribution match the expected distribution? | Chi-Square Goodness of Fit | `chisquare` |
| Are two categorical variables independent? | Chi-Square Test of Independence | `chi2_contingency` |

## Your Turn! (For Q&A)

Now it's your time to explore this dataset and answer questions using the appropriate statistical tests.

In [50]:
df= pd.read_csv('employee_data.csv')
df.head(20)

,Age,Years_Experience,Monthly_Salary,Monthly_Sales,Gender,Department,Marital_Status,Bonus_Received,Job_Satisfaction,City
0,60,20.7,36.2,23,Female,Sales,Married,No,High,Mashhad
1,50,23.7,39.1,30,Male,Finance,Married,Yes,Low,Tehran
2,36,0.6,31.6,27,Female,Marketing,Married,No,Low,Tehran
3,29,17.9,38.5,36,Male,Finance,Married,Yes,Low,Tehran
4,42,7.9,91.5,34,Female,Sales,Married,Yes,High,Tehran
5,60,22.6,36.4,21,Male,Sales,Married,No,High,Tehran
6,40,6.1,58.7,22,Male,Sales,Married,No,Medium,Mashhad
7,44,24.2,106.0,21,Male,HR,Single,No,Medium,Tehran
8,32,13.5,32.1,18,Female,Marketing,Single,No,Medium,Tehran
9,32,32.8,103.3,19,Male,Finance,Single,No,High,Shiraz
10,45,4.8,55.4,27,Female,Marketing,Married,No,Medium,Isfahan
11,57,11.9,40.6,23,Male,Finance,Single,No,Low,Shiraz
12,45,4.0,92.7,25,Male,Sales,Married,Yes,Low,Tehran
13,24,32.4,86.6,19,Male,Finance,Married,No,Low,Isfahan
14,43,30.7,109.0,12,Female,IT,Single,No,Medium,Tehran
15,23,9.0,96.2,21,Male,IT,Married,No,High,Tehran
16,45,23.1,102.3,17,Female,IT,Single,No,Medium,Mashhad
17,51,28.6,55.4,24,Female,IT,Married,No,Low,Tehran
18,59,19.4,46.0,23,Female,HR,Single,No,Low,Isfahan
19,23,18.5,97.6,28,Male,Sales,Married,Yes,High,Isfahan